"""grupo economico

Revision ID: 1ad7b9ca9a6d
Revises: f5e584f92370
Create Date: 2026-07-31 19:13:19.990965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad7b9ca9a6d'
down_revision: Union[str, Sequence[str], None] = 'f5e584f92370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.add_column('companies', sa.Column('economic_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'economic_groups', ['economic_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'economic_group_id')
    op.drop_table('economic_groups')
    # ### end Alembic commands ###
