"""grupo economico en factura

Revision ID: c14e188ff7d3
Revises: 1ad7b9ca9a6d
Create Date: 2026-08-04 13:25:55.398180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14e188ff7d3'
down_revision: Union[str, Sequence[str], None] = '1ad7b9ca9a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('economic_group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invoices_economic_group_id'), 'invoices', ['economic_group_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'economic_groups', ['economic_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_economic_group_id'), table_name='invoices')
    op.drop_column('invoices', 'economic_group_id')
    # ### end Alembic commands ###
