"""modelo inicial

Revision ID: f5e584f92370
Revises: 
Create Date: 2026-07-28 20:46:51.593702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5e584f92370'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_normalizado')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('gcs_path', sa.String(length=500), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('budget_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('cost_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('categoria_padre_id', sa.Integer(), nullable=True),
    sa.Column('codigo_erp', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_padre_id'], ['expense_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_categories_codigo_erp'), 'expense_categories', ['codigo_erp'], unique=False)
    op.create_table('import_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('origen', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('validation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('condicion_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('alias_texto', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_texto')
    )
    op.create_table('import_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('gcs_path', sa.String(length=500), nullable=False),
    sa.Column('hash_archivo', sa.String(length=64), nullable=True),
    sa.Column('subido_por_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subido_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_files_hash_archivo'), 'import_files', ['hash_archivo'], unique=False)
    op.create_table('import_template_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('mapeo_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('formato_fecha', sa.String(length=50), nullable=True),
    sa.Column('separador_decimal', sa.String(length=5), nullable=True),
    sa.Column('vigente_desde', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['import_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=255), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('categoria_principal_id', sa.Integer(), nullable=True),
    sa.Column('moneda_habitual', sa.String(length=10), nullable=True),
    sa.Column('condiciones_comerciales', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_principal_id'], ['expense_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_cuit'), 'providers', ['cuit'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('version_objetivo', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_version_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('business_unit_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('periodicidad_original', sa.String(length=20), nullable=True),
    sa.Column('importe_original', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('importe_mensual_equivalente', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['budget_version_id'], ['budget_versions.id'], ),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_anio'), 'budgets', ['anio'], unique=False)
    op.create_index(op.f('ix_budgets_mes'), 'budgets', ['mes'], unique=False)
    op.create_index(op.f('ix_budgets_provider_id'), 'budgets', ['provider_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_file_id', sa.Integer(), nullable=False),
    sa.Column('template_version_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('resumen_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('aprobado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['import_file_id'], ['import_files.id'], ),
    sa.ForeignKeyConstraint(['template_version_id'], ['import_template_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('alias_texto', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_aliases_alias_texto'), 'provider_aliases', ['alias_texto'], unique=True)
    op.create_table('requirement_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('valor_anterior_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('valor_nuevo_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_accion'), 'audit_events', ['accion'], unique=False)
    op.create_index(op.f('ix_audit_events_entidad'), 'audit_events', ['entidad'], unique=False)
    op.create_index(op.f('ix_audit_events_entidad_id'), 'audit_events', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_audit_events_fecha'), 'audit_events', ['fecha'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('business_unit_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('numero_factura', sa.String(length=50), nullable=True),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('letra_arca', sa.String(length=5), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('importe_neto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('impuestos', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('importe_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('tasa_cambio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('importe_en_dolares', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('orden_compra', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('cae', sa.String(length=30), nullable=True),
    sa.Column('identificador_externo_tsdocs', sa.String(length=50), nullable=True),
    sa.Column('link_documento_original', sa.String(length=500), nullable=True),
    sa.Column('usuario_aprobador_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['usuario_aprobador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_area_id'), 'invoices', ['area_id'], unique=False)
    op.create_index(op.f('ix_invoices_branch_id'), 'invoices', ['branch_id'], unique=False)
    op.create_index(op.f('ix_invoices_business_unit_id'), 'invoices', ['business_unit_id'], unique=False)
    op.create_index(op.f('ix_invoices_category_id'), 'invoices', ['category_id'], unique=False)
    op.create_index(op.f('ix_invoices_company_id'), 'invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoices_cost_center_id'), 'invoices', ['cost_center_id'], unique=False)
    op.create_index(op.f('ix_invoices_fecha_emision'), 'invoices', ['fecha_emision'], unique=False)
    op.create_index(op.f('ix_invoices_identificador_externo_tsdocs'), 'invoices', ['identificador_externo_tsdocs'], unique=False)
    op.create_index(op.f('ix_invoices_numero_factura'), 'invoices', ['numero_factura'], unique=False)
    op.create_index(op.f('ix_invoices_provider_id'), 'invoices', ['provider_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_item', sa.Text(), nullable=True),
    sa.Column('importe', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staging_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('datos_crudos_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('datos_mapeados_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('estado_fila', sa.String(length=30), nullable=False),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('procesado_por_id', sa.Integer(), nullable=True),
    sa.Column('procesado_en', sa.DateTime(), nullable=True),
    sa.Column('es_duplicado_de_invoice_id', sa.Integer(), nullable=True),
    sa.Column('motivo_cambio_categoria', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['es_duplicado_de_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['procesado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staging_invoice_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('aceptado_por_id', sa.Integer(), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aceptado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staging_invoice_id'], ['staging_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_errors')
    op.drop_table('staging_invoices')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_invoices_provider_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_numero_factura'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_identificador_externo_tsdocs'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_fecha_emision'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_cost_center_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_company_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_category_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_business_unit_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_branch_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_area_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_audit_events_fecha'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entidad_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entidad'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_accion'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('requirement_comments')
    op.drop_index(op.f('ix_provider_aliases_alias_texto'), table_name='provider_aliases')
    op.drop_table('provider_aliases')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_budgets_provider_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_mes'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_anio'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_table('user_roles')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_providers_cuit'), table_name='providers')
    op.drop_table('providers')
    op.drop_table('import_template_versions')
    op.drop_index(op.f('ix_import_files_hash_archivo'), table_name='import_files')
    op.drop_table('import_files')
    op.drop_table('area_aliases')
    op.drop_table('validation_rules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('projects')
    op.drop_table('import_templates')
    op.drop_index(op.f('ix_expense_categories_codigo_erp'), table_name='expense_categories')
    op.drop_table('expense_categories')
    op.drop_table('cost_centers')
    op.drop_table('companies')
    op.drop_table('business_units')
    op.drop_table('budget_versions')
    op.drop_table('branches')
    op.drop_table('attachments')
    op.drop_table('areas')
    # ### end Alembic commands ###
